### PR TITLE
ClearOutside & TimeDate implementation

### PR DESCRIPTION
**Pull request by DenizUgur**
## ClearOutside
This page has ratings of weather for cloud coverage (a must for stargazers) over every hour.

```diff
+ Green flashing lines represent open skies for the week ahead
```

## Time&Date
This page has lots of information about time, date, year... 😄 It has information about moon phases too.

### Colors and their meanings has been listed bellow

| Color | State |
|:-----------|:------------|
| black-white       |        First Quater |     
| white     |      Full Moon |    
| white-black       |        Third Quater |     
| black         |          New Moon | 

# [Current Release](https://github.com/DenizUgur/horizontal-calendar-widget/releases/tag/1.1)
screen shot 2017-02-12 at 23 31 05

### CODE REVIEW

**Comment by JohnKacz** [comment]
What if you used variables for LAT, LONG, county, and city? I think that would make it clearer for new users that then need to update those for their location. Also I would recommend using defaults for those variables so the script works right away but will likely have invalid data for most users.

At the very least you should have coments in the code like you do in the pull request AND make changes to the README as well in this pull request.

I would make try to make the changes myself but I'm not enough of a github power user to know how to modify a pull request on another users repo.

**Comment by DenizUgur** [comment]
I've tried to implement variables for those 4 variables but I couldn't figure it out how. If you can help me with that, I would love to make the changes myself. I'm not really good with github either but I think if you request a pull from this repo and if I confirm that request your implementations would be saved to this repo. You can request a pull from either GitHub Web or from desktop app.

**Comment by JohnKacz** [comment]
Most of my Übersicht widgets are in coffeescript so I use string interpolation but in plain js you should be able to just use `var LAT = '33.25';`

    # coffeescript example
    LAT     = '41.88'
    LONG    = '-87.63'
    country = 'usa'
    city    = 'chicago'

    command: "curl -s 'https://clearoutside.com/forecast/#{LAT}/#{LONG}?view=midnight' 'https://www.timeanddate.com/moon/#{country}/#{city}'"

So I imagine this should work
    
    var LAT     = '41.88';
    var LONG    = '-87.63';
    var country = 'usa';
    var city    = 'chicago';
    
    command: "curl -s 'https://clearoutside.com/forecast/"+LAT+"/"+LONG+"?view=midnight' 'https://www.timeanddate.com/moon/"+country+"/"+city,

**Comment by DenizUgur** [comment]
Got it, I'll make the adjustments to the code and README file when I get to home. Probably in a hour or so.

**Comment by ashikahmad** [comment]
The idea looks cool. By the way, I wanted to keep it simple. But as it looks like some people wants weather data integrated, I need to come up with a decision.

Is it better to keep it simple (and without any network request) or with subtle weather information attached? Please, give your suggestions.

**Comment by ashikahmad** [comment]
By the way, I'm also eagerly waiting for your update 👍

**Comment by DenizUgur** [comment]
Actually I thought about that too. My idea was to create one another row and show sunny days with yellow color, rainy days with blue color. Also if this idea is integrated to the code, I needed to make the ClearOutside request to gather information about clouds only after sunset hours.
I'll make the adjustment we talked above today. If you liked my idea about weather, either you can do it or I can do it later in June. I have a very important exam coming up so I'm not really available for any other stuff.

**Comment by JohnKacz** [comment]
@DenizUgur Good stuff! Remember to test it out because as I mentioned I'm not an pro.

As for keeping it simple I agree with @ashikahmad. Maybe the code could be reorganized to group the weather stuff with it commented out by default? Then with comments you could instruct users how to add the extra info with a disclaimer about hitting the network?

Alternatively, I think you could just make sub-widgets where the main hcal widget is made of two widgets (the old hcal widget and the new weather related data). See this project as an example of a widget set ([sys-mon-set](https://github.com/felixhageloh/uebersicht-widgets/tree/master/sys-mon-set))

**Comment by DenizUgur** [comment]
@JohnKacz I couldn't do the variable part.
```javascript
LAT: "37.01",
LONG: "27.21",
country: "usa",
city: "miami",
command: "curl -s 'https://clearoutside.com/forecast/\'" + this.LAT + "\'/\'" + this.LONG + "\'?view=midnight' 'https://www.timeanddate.com/moon/\'" + this.country + "\'/\'" + this.city + "\''",
```
Can you help me?
I tried the [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) but it looks like Übersicht doesn't support it.

**Comment by JohnKacz** [comment]
@DenizUgur I spent some time trying to get it to work as well but with no success. I've got it working fine on a coffeescript version of the same code. @ashikahmad would you be willing for me to make a pull request with an index.coffee instead?

If not I suppose the original pull request with better documentation for changing the string is good enough.

OT: @DenizUgur I like your setup from the screenshot, would you be willing to share with me your other Übersicht widgets?

**Comment by DenizUgur** [comment]
@JohnKacz Of course. You can download this [zip file containing my setup](https://www.dropbox.com/s/threukihszazpg1/widgets.zip?dl=0)

**Comment by DenizUgur** [comment]
```javascript

lat: "",
long: "",
country: "",
city: "",
    
command: 'curl -s "https://clearoutside.com/forecast/'+ this.lat +'/'+ this.long +'?view=midnight" "https://www.timeanddate.com/moon/'+ this.country +'/'+ this.city +'"',

```

I've done this but string are not being defined. @ashikahmad any idea how to achive this?

**Comment by JohnKacz** [comment]
@DenizUgur Yes that's what I was trying. The problem seems to be that since "widgets are serialized to plain objects" the object properties are not initialized when 'command' is being serialized I guess. I even tried making lat, long, etc functions that would return the correct string but it doesn't matter.

**Comment by DenizUgur** [comment]
@JohnKacz ~~Is it possible to send an AJAX request inside update function?~~ Would this way be reliable?
Edit: links are https secured so I guess that would be impossible.

**Comment by DenizUgur** [comment]
@ashikahmad I have made the modifications you wanted including updated readme file with new screenshot. @JohnKacz I executed the main command inside `update` so that I can set variables.

**Comment by ashikahmad** [comment]
Thanks for all this efforts @DenizUgur 👍 .  I am a bit busy today. Hope I can check & merge it tomorrow. Thanks again for such a contribution 😄

**Comment by itz-atomic** [comment]
Is there a download for this edited widget? Looks really cool!

**Comment by DenizUgur** [comment]
@itz-atomic I will make a release on my repo and add the link here as well. Unfortunately I'm not at home atm, so I will do it when I get home.

**Comment by DenizUgur** [comment]
@itz-atomic You can download js file from [this link](https://github.com/DenizUgur/horizontal-calendar-widget/releases/tag/1.1)

**Pull request closed without merging**
